### ISSUE TITLE
Bayeux elixir client?

### ISSUE THREAD

**Issue by thbar** [messagerocket/pixie#1]
I just stumbled upon pixie and I've been digging into the code, but I'm wondering : did you implement some sort of Bayeux client in elixir, either in this repo (but I don't think it's there) or somewhere else?  Thanks!

**Comment by jimsynz** [comment]
no, but it's been on my list for some time. my use-case so far has been using the Faye JS and Ruby clients.

**Comment by thbar** [comment]
Ok, thanks for the update! Closing for now!
