### ISSUE TITLE
Example?

### ISSUE THREAD

**Issue by cpursley** [messagerocket/pixie#3]
I'm considering using this to replace an existing node.js faye server.

Is there a full example of how to set up a simple pixie server?

**Comment by jimsynz** [comment]
Not really. I'd start with `mix pixie.server` and give it a try.  I'd welcome PR's with documentation improvements.

**Comment by cpursley** [comment]
Thanks. Happy to help update dependencies and docs.

I ran `mix pixie.server` (after updating timex). I'm trying this as a drop-in replacement for faye (node/ruby). It's trying to communicate, but I'm getting the following error message when pointing the Client at `localhost:4000/faye`:

```base
General
Request URL:http://localhost:4000/faye?message=%5B%7B%22channel%22%3A%22%2Fmeta%2Fhandshake%22%2C%22version%22%3A%221.0%22%2C%22supportedConnectionTypes%22%3A%5B%22websocket%22%2C%22eventsource%22%2C%22long-polling%22%2C%22cross-origin-long-polling%22%2C%22callback-polling%22%5D%2C%22id%22%3A%221%22%7D%5D&jsonp=__jsonp11__
Request Method:GET
Status Code:404 Not Found
Remote Address:127.0.0.1:4000
Referrer Policy:no-referrer-when-downgrade
```

And

```bash
Query String Paramaters
message:[{"channel":"/meta/handshake","version":"1.0","supportedConnectionTypes":["websocket","eventsource","long-polling","cross-origin-long-polling","callback-polling"],"id":"1"}]
jsonp:__jsonp11__
```

Any pointers are much appreciated.

**Comment by jimsynz** [comment]
It's been a while since I worked on it, but I think the default endpoint for `mix pixie.server` is `/pixie` or perhaps just `/`.
